import type { Metadata } from "next";
import { Sidebar } from '../../dashboard/components/Sidebar';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <main>
      <div className="antialiased bg-gray-900 w-full min-h-screen text-slate-300 relative py-4 px-4">
        <div className="grid grid-cols-12 mx-auto gap-2 sm:gap-4 md:gap-6 lg:gap-10 xl:gap-14 max-w-7xl my-10 px-2">


          <Sidebar />
  

          <div className="col-span-9 rounded-lg">
            { children }
          </div>
        </div>
      </div>
    </main>
  );
}
